#image: node:7.5.0

variables:
  CI_BUILD_NAME: "build"
 
stages:
  - build
  - deploy
  

build:
  type: build
  cache:
    key: "$CI_BUILD_NAME"
    untracked: false
    paths:
        - build/js
    
  script:
    - mkdir build/js
    - ls build

deploy:
  type: deploy
  cache: 
    key: "$CI_BUILD_NAME" 
  script:
  - ls build
