#image: node:7.5.0

stages:
  - build
  - deploy
  

build:
  type: build
  cache:
    key: "deploy"
    untracked: true
    paths:
        - build/js
    
  script:
    - mkdir build/js
    - ls build

deploy:
  type: deploy
  script:
  - ls build
