image: node:7.5.0

stages:
  - build
  - deploy

build:
  type: build
  script:
  - npm install --only=dev
  - npm install webpack -g
  - npm run webpack:build
  - ls build/js


deploy:
  type: deploy
  image: ruby:2.3.3
  script:
  - ls build/js
  only:
  - master
