image: node:7.5.0

stages:
  - build
  - deploy

build:
  type: build
  cache:
    paths:
      - node_modules/
      - build/js
  script:
    - mkdir build/js
    ls build

deploy:
  type: deploy
  script:
  - ls build
