#image: node:7.5.0

variables:
  CI_BUILD_NAME: "build"
  
cache:
key: "$CI_BUILD_NAME"
untracked: true
paths:
    - build/js
    
stages:
  - build
  - deploy
  

build:
  type: build
  script:
    - mkdir build/js
    - ls build

deploy:
  type: deploy
  script:
  - echo "${CI_BUILD_NAME}"
  - ls build
