image: node:7.5.0

stages:
  - build
  - deploy
  
cache:
  paths:
    - build/js

build:
  type: build
  script:
  - npm install --only=dev
  - npm install webpack -g
  - npm run webpack:build
  
  

deploy:
  type: deploy
  script:
  - ls build
