image: node:7.5.0

stages:
  - test
  - build
  - deploy

test:
  type: test
  script:
  - apt-get update -qy
  - npm install
  - node app.js

build:
  type: build
  script:
  - npm install --only=dev
  - npm install webpack -g
  - npm run webpack:build

deploy:
  type: deploy
  image: ruby:2.3.3
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --skip_cleanup=true --app=hackdo-website --api-key=$HEROKU_STAGING_API_KEY
  - cd build/js && ls
  only:
  - master
