#image: node:7.5.0

variables:
  CI_BUILD_NAME: "deploy"
  
    
stages:
  - build
  - deploy

cache:
    key: "$CI_BUILD_NAME"
    untracked: true
    paths:
      - build/js

build:
  type: build
  script:
    - mkdir build/js
    - ls build

deploy:
  type: deploy
  script:
  - echo "${CI_BUILD_NAME}"
  - ls build
