image: node:7.5.0

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/
    - build/js

build:
  type: build
  script:
    - mkdir build/js

deploy:
  type: deploy
  script:
  - ls build
